title = "Toml Config for Mongo"

[owner]
name = ""


[mongoAuth]
    [mongoAuth.Neptune]
    userName = ""
    pwd = ""  
    
[mongoConfig]
    db = ""
    collection = ""

[sites]
    [sites.wex]
    tradeUrl= "https://wex.nz/tapi"